apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
- ../crds
- istio-ambient.yaml

# istioctl manifest generate --set profile=ambient > istio-ambient.yaml
