---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: prodlab
        overlay: prod
      - cluster: testlab
        overlay: test
  template:
    metadata:
      name: "{{overlay}}-istio"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: "{{overlay}}"
      ignoreDifferences: []
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 5m
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
      source:
        repoURL: https://github.com/Dayzpd/kustomize-istio
        targetRevision: HEAD
        path: "overlays/{{overlay}}"
      destination:
        name: "{{cluster}}"
        namespace: istio-system
